development:
  adapter: postgresql
  database: atm_finder_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: atm_finder_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: atm_finder_production
  pool: 5
  timeout: 5000
