development:
  adapter: postgis
  database: atm_finder_development
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  timeout: 5000

test:
  adapter: postgis
  database: atm_finder_test
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  timeout: 5000

production:
  adapter: postgis
  database: atm_finder_production
  postgis_extension: true
  schema_search_path: public,postgis
  pool: 5
  timeout: 5000
